clubsportal/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from home import views as home_views
from registration import views as register_views
from django.conf import settings
from django.conf.urls.static import static
from userprofile import views as profile_views
from forum import views as forum_views
from events import views as events_views
from propose_join import views as clubs_views
from forum import views as forum_views
from django.conf.urls import url
from notifications import views as notify_views
from administration import views as admin_views

from rest_framework_jwt.views import obtain_jwt_token


urlpatterns = [
    path('admin/', admin.site.urls),
    path('administration/', admin_views.index, name="admin_page"),
    path('',home_views.index, name='home'),
    path('propose_join/',include("propose_join.urls")),
    path('registration/',include("registration.urls")),
    path('userprofile/',include("userprofile.urls")),
    path('home/', include("forum.urls")),
    path('administration/', include("administration.urls")),
    path('home/clubs', clubs_views.existingClubList, name='exlist'),
    path('home/proposed-clubs', clubs_views.proposedClubList, name='prlist'),
    path('home/joined-clubs', clubs_views.joinedClubList, name='jdlist'),
    path('home/joined-clubs/<int:club_id>/', forum_views.forum_of_club, name='club_forum'),
    path('home/joined-clubs/<int:club_id>/add-event/', forum_views.event_of_club, name='club_event'),
    path('home/joined-clubs/<int:club_id>/list_events/', events_views.list_event_of_club, name='list_club_event'),
    path('home/joined-clubs/<int:event_id>/about', events_views.event_detail1, name='event_detail1'),
    path('home/joined-clubs/<int:club_id>/<int:thread_id>/', forum_views.posts_of_club, name='club_forum_posts'),
    path('home/propose-club', clubs_views.proposeClub, name='prclub'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/',register_views.register, name = 'register'),
    path('home/profile/',profile_views.profile, name = 'profile'),
    path('api/events/',include("events.api.urls")),
    path('api-token-auth/', obtain_jwt_token),
    path("home/profile/change_password",profile_views.change_password, name="change_password"),
    path('emailverify/',register_views.emailverify, name = 'emailverify'),
    path('resetpassword/',register_views.resetpassword,name = 'resetpassword'),
    path('verifyemail/',register_views.verifyemail, name = 'verifyemail'),
    path('reset_password/',register_views.reset_password, name = 'reset_password'),
    path("send",notify_views.send,name='send'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

"""
curl -X POST -d "username=rahul_admin&password=test1234" http://localhost:8000/api-token-auth/
curl -H "Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwidXNlcm5hbWUiOiJyYWh1bF9hZG1pbiIsImV4cCI6MTU0NDU2Njc4NywiZW1haWwiOiIifQ.2GoWR9hSMATuh7oVk8f7LzPlxhDn78_mmvr0Tj1A5Hc" http://127.0.0.1:8000/api/events/

"""

forum/urls.py
from django.urls import path
from . import views
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    like_post,
)

urlpatterns = [
    path('', views.index, name ='user-home'),
    path('post/<int:pk>/', views.post_detail, name ='post-detail'),
    path('like/', views.like_post, name ='like_post_url'),
    path('post/new/', PostCreateView.as_view(), name ='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('notifications/' , views.notifications, name = 'notifications'),
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("",views.index)
]

propose_join/urls.py
from django.urls import path
from . import views

app_name= "propose_join"    
urlpatterns=[
   # path('button', views.proposeClub, name='button'),
   # path('list', views.list, name='list'),
    path('home/proposed-clubs/add', views.voting, name='voting'),
    #path('detailview/remove', views.votedown, name='votedown'),
    #path('existing',views.existingclub,name='existing'),
    #path('existing/count', views.passed, name='passed'),
    path('existing/add', views.add_to_join, name='add_to_join'),
    #path('myclub', views.joined, name='myclub'),
    path('detailview/<int:pk>/', views.ProposedClubDetailView.as_view(), name='detailview'),
    path('detailview2/<int:pk>/', views.JoinedClubDetailView.as_view(), name='detailview2'),
    path('detailview2/<int:pk>/rem',views.quitclub,name='quitclub'),
    path('clubmembers/<int:pk>/', views.ListCLubMembers, name="listmem"),



]

notifications/models.py
from django.db import models

# Create your models here.
class Notification(models.Model):
    username = models.CharField(max_length=100 ,default='')
    sender = models.CharField(max_length=100,default='')
    notifications = models.CharField(max_length=1000,null=True)
    date = models.CharField(max_length=50,default='')

    def __str__(self):
        return self.username

forum/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post, Comments
from django.core.paginator import Paginator

class Add_Post(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':'3'}))
    class Meta:
        model = Post
        fields=['title','content']

class Add_Comment(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':'3'}))
    class Meta:
        model = Comments
        fields=['content']

class Search_Post(forms.Form):
    search_post = forms.CharField(max_length=100)

forum/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse,JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    RedirectView
)
from .models import Post, Comments, NotificationsPost, NotificationsEvents
from .forms import Add_Post,Add_Comment,Search_Post
from events.forms import AddEventForm
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from propose_join.models import ExistingClub
from django.db.models import Q
from events.models import Events
from django.template.loader import render_to_string
from itertools import chain
from operator import attrgetter

# Create your views here.
@login_required
def index(request):
    cuser = request.user
    PNoti = NotificationsPost.objects.filter(user = cuser).filter(read = False)
    ENoti = NotificationsEvents.objects.filter(user = cuser).filter(read = False)
    count = PNoti.count() + ENoti.count()
    club = ExistingClub.objects.get(club_name='Global')
    if request.method == 'POST':
        form = Add_Post(request.POST or None)
        form1 = Search_Post(request.POST or None)
        if form.is_valid():
            content = request.POST.get('content')
            title = request.POST.get('title')
            form = Post.objects.create(title=title, author=request.user, content=content, in_club=club)
            form.save()
            messages.success(request, f'Posted')
            return redirect('user-home')
        if form1.is_valid() and (form.is_valid() == False):
            form=Add_Post()
            search_post = request.POST.get('search_post')
            posts = Post.objects.filter(in_club=ExistingClub.objects.get(club_name='Global')).filter(Q(title__icontains=search_post) | Q(content__icontains=search_post)).order_by('-date_posted')
            paginator = Paginator(posts,5)
            page = request.GET.get('page')
            posts = paginator.get_page(page)
            context = {
                'posts': posts,
                'form' : form,
                'form1':form1,
                'count':count,
            }
            return render(request,'forum/index.html', context)


        elif form1.is_valid() and form.is_valid():
            posts = Post.objects.filter(in_club=ExistingClub.objects.get(club_name='Global')).order_by('-date_posted')
            paginator = Paginator(posts,5)
            page = request.GET.get('page')
            posts = paginator.get_page(page)
            context = {
                'posts': posts,
                'form' : form,
                'form1':form1,
                'count':count,
            }
            return render(request,'forum/index.html', context)

    else:
        form=Add_Post()
        form1=Search_Post()

    posts = Post.objects.filter(in_club=ExistingClub.objects.get(club_name='Global')).order_by('-date_posted')
    paginator = Paginator(posts,5)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    context = {
        'posts': posts,
        'form' : form,
        'form1':form1,
        'count':count,
    }
    return render(request,'forum/index.html', context)


def post_detail(request, pk):
    is_liked = False
    post = get_object_or_404(Post, pk=pk)
    if post.likes.filter(id=request.user.id):
        is_liked = True
    comments = Comments.objects.filter(comment_to=post).order_by('-date_posted')
    paginator = Paginator(comments,10)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    if request.method == 'POST':
        form = Add_Comment(request.POST or None)
        if form.is_valid():
            content = request.POST.get('content')
            form = Comments.objects.create(comment_to=post, author=request.user, content=content)
            form.save()
            con = "Someone Commented on your Post"
            note = NotificationsPost.objects.create(postid = post,content = con,user = post.author,read = False)
            note.save()
            messages.success(request, f'Comment Posted')
            return redirect('post-detail', pk=pk)
    else:
        form=Add_Comment()
    context = {
        'post' : post,
        'comments' : comments,
        'form' : form,
        'total_likes': post.total_likes(),
        'is_liked': is_liked,
    }
    return render(request,'forum/post_detail.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'forum/index.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']

class PostDetailView(DetailView):
    model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/home'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

def forum_of_club(request, club_id):
    object = ExistingClub.objects.get(pk = club_id)
    if request.method == 'POST':
        form = Add_Post(request.POST or None)
        form1 = Search_Post(request.POST or None)
        if form.is_valid():
            content = request.POST.get('content')
            title = request.POST.get('title')
            in_club = get_object_or_404(ExistingClub, pk=club_id)
            form = Post.objects.create(title=title, author=request.user, content=content, in_club=in_club)
            form.save()
            messages.success(request, f'Posted')
            return redirect('club_forum' ,club_id=club_id)
        if form1.is_valid() and (form.is_valid() == False):
            form=Add_Post()
            search_post = request.POST.get('search_post')
            posts = Post.objects.filter(in_club=ExistingClub.objects.get(pk=club_id)).filter(Q(title__icontains=search_post) | Q(content__icontains=search_post)).order_by('-date_posted')
            paginator = Paginator(posts,5)
            page = request.GET.get('page')
            posts = paginator.get_page(page)
            in_club = [get_object_or_404(ExistingClub, pk=club_id)]
            context = {
                'posts': posts,
                'form' : form,
                'form1':form1,
                'inclub':in_club,
                'object':object,
            }
            return render(request,'forum/club_forum.html', context)


        elif form1.is_valid() and form.is_valid():
            posts = Post.objects.filter(in_club=ExistingClub.objects.get(pk=club_id)).order_by('-date_posted')
            paginator = Paginator(posts,5)
            page = request.GET.get('page')
            posts = paginator.get_page(page)
            in_club = [get_object_or_404(ExistingClub, pk=club_id)]
            context = {
                'posts': posts,
                'form' : form,
                'form1':form1,
                'inclub':in_club,
                'object':object,
            }
            return render(request,'forum/club_forum.html', context)

    else:
        form=Add_Post()
        form1=Search_Post()

    posts = Post.objects.filter(in_club=ExistingClub.objects.get(pk=club_id)).order_by('-date_posted')
    paginator = Paginator(posts,5)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    in_club = [get_object_or_404(ExistingClub, pk=club_id)]
    context = {
        'posts': posts,
        'form' : form,
        'form1':form1,
        'inclub':in_club,
        'object':object,
    }
    return render(request,'forum/club_forum.html', context)

def posts_of_club(request, club_id, thread_id):
    pass

@login_required
def like_post(request):
    print(request.POST.get('id'))
    post = get_object_or_404(Post, pk=request.POST.get('id'))
    is_liked = True
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        con = "Someone Liked your Post"
        note = NotificationsPost.objects.create(postid = post,content = con,user = post.author,read = False)
        note.save()
        is_liked = True
    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes':post.total_likes(),
    }
    if request.is_ajax():
        html = render_to_string('forum/like_section.html',context,request=request)
        return JsonResponse({'form':html})


def event_of_club(request, club_id):
    if request.method == 'POST':
        form3 = AddEventForm(request.POST or None)
        if form3.is_valid():
            event_name = request.POST.get('event_name')
            about_event = request.POST.get('about_event')
            event_from = request.POST.get('event_from')
            event_to = request.POST.get('event_to')
            venue = request.POST.get('venue')
            in_club = get_object_or_404(ExistingClub, pk=club_id)
            form3 = Events.objects.create(event_name =event_name, about_event =about_event, event_from=event_from, event_to=event_to, venue=venue, in_club=in_club)
            form3.save()
            con = "An Event was announced in your club"
            for i in in_club.club_members.all():

notifications/views.py
from django.shortcuts import render
from .models import Notification
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import datetime
from django.utils import timezone
from django.core.mail import EmailMessage
from django.contrib import messages
from django.shortcuts import render, redirect# Create your views here.
@login_required(login_url="{% url 'login' %}")
def notifications(request):
    current_user = request.user
    username=str(current_user)
    notif=Notification.objects.filter(username=username)
    return render(request, 'notifications/view_notify.html',{'notification':notif})

@login_required(login_url="{% url 'login' %}")
def send(request):
    if request.method == 'POST':
        notf=request.POST.get('notf')
        users=request.POST.getlist('selected_users')
        list=[]
        for user in users:
            list.append(User.objects.get(username=user).email)
        mail = EmailMessage('Notification', notf , to=list)
        mail.send()

        current_user=request.user
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        sender=str(current_user)
        for name in users:
            new=Notification.objects.create(username=name,sender=sender,notifications=notf,date=str(now))
            new.save()
        messages.success(request, f'Notification sent successfully')
        return redirect('notifications')
    else:
        users=User.objects.all()
        context={
            'users':users
        }
        return render(request,'notifications/send.html',context)

forum/templates/forum/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="{% static 'forum/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'forum/css/style.css' %}">
    <style>
      a {
        color: #428bca;
      }
      a:hover {
          color: #333;
          text-decoration: none;
      }

      .dropdown {
          position: relative;
          display: inline-block;
      }

      .dropdown-content {
          display: none;
          position: absolute;
          background-color: #f1f1f1;
          min-width: 130px;
          box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
          z-index: 1;
      }

      .dropdown-content a {
          display: block;
      }

      .dropdown-content a:hover {background-color: #ddd;}

      .dropdown:hover .dropdown-content {display: block;}

      .navbar_bgcolor{
        background-color:#001a33;
      }

      .jumbotron{
	      background-image : url("https://png.pngtree.com/thumb_back/fw800/back_pic/04/48/50/00585a3568a0a7d.jpg");
        background-size: cover;
      }
      </style>
  </head>
  <body>
      <header class="site-header">
          <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top" style="background-color:#001a33;">
            <div class="container">
              <a class="navbar-brand mr-4" href="{% url 'user-home' %}">CLUBSportal</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                  <div class="dropdown">
                    <a class="nav-item nav-link dropbtn" data-toggle="dropdown">Clubs</a>
                    <div class="dropdown-content">
                      <a class="nav-item nav-link" style="color:#001a33" href="{% url 'jdlist' %}">Joined Clubs</a>
                      <a class="nav-item nav-link" style="color:#001a33" href="{% url 'exlist' %}">Existing Clubs</a>
                      <a class="nav-item nav-link" style="color:#001a33" href="{% url 'prlist' %}">Proposed Clubs</a>
                    </div>
                  </div>
                  <a class="nav-item nav-link" href="{% url 'prclub' %}">Propose Club</a>
                  {% if request.user.is_superuser %}
                    <a class="nav-item nav-link" href="{% url 'admin_page' %}">Admin</a>
                  {% endif %}
                  <!--<a class="nav-item nav-link " href="{% url 'post-create' %}">New Post</a>-->
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                  {% if user.is_authenticated %}
                    <a class="nav-item" href="{% url 'profile' %}"> <img class="rounded-circle" style="height: 40px; width: 40px; margin-right: 10px ; margin-top: 1px" src="{{ user.profile.image.url }}"> </a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                  {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </nav>
        </header>
      {% block body %}
      {% endblock %}
      <main role="main" class="container">
          <div class="row">
            <div class="col-md-8">
                {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{message}}
                    </div>
                {% endfor  %}
            {% endif %}
              {% block posts %}{% endblock %}
              {% block comments %}{% endblock %}
            </div>
            <div class="col-md-4">
              <div class="content-section">
                <h3>Our Sidebar</h3>
                {% block link  %}{% endblock %}
              </div>
            </div>
          </div>
        </main>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function (event) {

                    $(document).on('click','#like',function (event) {
                        event.preventDefault();
                        var pk = $(this).attr('value');
                        $.ajax({
                            type:'POST',
                            url: "{% url 'like_post_url' %}",
                            data: {'id':pk,'csrfmiddlewaretoken':'{{ csrf_token }}'},
                            success:function (response) {
                                $('#like_section').html(response['form'])
                            },
                            error: function (rs, e) {
                                console.log(rs.responseText);
                            },
                        })
                    })
                })
      </script>

  </body>
</html>

  </body>
</html>

forum/templates/forum/club_forum.html
{% extends "forum/base.html" %}
{% load crispy_forms_tags %}
{% block body %}
{% endblock %}
{% block posts %}
<div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ object.club_logo.url }}">
      <div class="media-body">
        <h2 class="account-heading">{{ object.club_name }}</h2>
        <p class="text-secondary">{{ object.club_info|truncatewords_html:50|urlize }}</p>
      </div>
    </div>
  </div>
  <div class = 'content-section' >
    <form method="POST">
        {% csrf_token %}
        <fieldset class='form-group' >
            <legend class='border-bottom mb-4'>What's on your Mind?</legend>
            {{form|crispy}}
        </fieldset>
        <div class='form-group'>
            <button class= 'btn btn-outline-info' type='submit'>Post</button>
        </div>
    </form>
  </div>
  <div class = 'content-section' >
    <form method="POST">
        {% csrf_token %}
        <fieldset class='form-group' >
            {{form1|crispy}}
        </fieldset>
        <div class='form-group'>
            <button class= 'btn btn-outline-info' type='submit'>Search</button>
        </div>
    </form>
  </div>
  <h2 class="article-title ml-2">Latest Posts!</h2>
    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content|truncatewords_html:50|urlize }}</p>
          </div>
        </article>
    {% endfor %}

    <div class='container text-center' >
      {% if posts.has_previous %}
        <a class= 'btn btn-outline-info'  href='?page={{ posts.previous_page_number }}'>Previous</a>
      {% endif %}
      {% if posts.has_next %}
        <a  class= 'btn btn-outline-info ml-5' href='?page={{ posts.next_page_number }}'>Next</a>
      {% endif %}
    </div>
    <div style="text-align:center;">...</div>

{% endblock %}

{% block link %}
  <p class='text-muted'>
    <ul class="list-group">
      <li class="list-group-item list-group-item-light">Latest Posts</li>
      <li class="list-group-item list-group-item-light">Top Clubs</li>
      <li class="list-group-item list-group-item-light">Top Posts</li>
      {% for club in inclub %}
      <li class="list-group-item list-group-item-light"><a href="{% url 'list_club_event' club.id %}">Show Event</a></li>
      <li class="list-group-item list-group-item-light"><a href="{% url 'propose_join:listmem' club.id %}">Club Members</a></li>
      {% if request.user in object.admin.all %}

      <li class="list-group-item list-group-item-light"><a class=" btn btn-outline-info" style="width: 100%;"href="{% url 'club_event' object.id %}">Add Event</a></li>
      {% endif %}
      {% endfor %}
    </ul>
  </p>

{% endblock %}

forum/templates/forum/index.html
{% extends "forum/base.html" %}
{% load crispy_forms_tags %}
{% block body %}
{% endblock %}
{% block posts %}

  <div class="jumbotron">
    <center><h1>Global Area</h1></center>
  </div>

  <div class = 'content-section' >
    <form method="POST">
        {% csrf_token %}
        <fieldset class='form-group' >
            <legend class='border-bottom mb-4'>What's on your Mind?</legend>
            {{form|crispy}}
        </fieldset>
        <div class='form-group'>
            <button class= 'btn btn-outline-info' type='submit'>Post</button>
        </div>
    </form>
  </div>
  <div class = 'content-section' >
    <form method="POST">
        {% csrf_token %}
        <fieldset class='form-group' >
            {{form1|crispy}}
        </fieldset>
        <div class='form-group'>
            <button class= 'btn btn-outline-info' type='submit'>Search</button>
        </div>
    </form>
  </div>
  <h2 class="article-title ml-2">Latest Posts!</h2>
    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content|truncatewords_html:50|urlize }}</p>
          </div>
        </article>
    {% endfor %}

    <div class='container text-center' >
      {% if posts.has_previous %}
        <a class= 'btn btn-outline-info'  href='?page={{ posts.previous_page_number }}'>Previous</a>
      {% endif %}
      {% if posts.has_next %}
        <a  class= 'btn btn-outline-info ml-5' href='?page={{ posts.next_page_number }}'>Next</a>
      {% endif %}
    </div>
    <div style="text-align:center;">...</div>

{% endblock %}
{% block link %}
  <p class='text-muted'>
    <ul class="list-group">
      <li class="list-group-item list-group-item-light"><a class=" btn btn-outline-info" style="width: 100%;"href="{% url 'notifications' %}">Notifications{%if count != 0%} <span class="badge badge-danger">{{count}}</span> {%endif%}</a></li>
    </ul>
  </p>

{% endblock %}