clubsportal/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from home import views as home_views
from registration import views as register_views
from django.conf import settings
from django.conf.urls.static import static
from userprofile import views as profile_views
from forum import views as forum_views
from events import views as events_views
from propose_join import views as clubs_views
from forum import views as forum_views
from django.conf.urls import url
from notifications import views as notify_views
from administration import views as admin_views

from rest_framework_jwt.views import obtain_jwt_token


urlpatterns = [
    path('admin/', admin.site.urls),
    path('administration/', admin_views.index, name="admin_page"),
    path('',home_views.index, name='home'),
    path('propose_join/',include("propose_join.urls")),
    path('registration/',include("registration.urls")),
    path('userprofile/',include("userprofile.urls")),
    path('home/', include("forum.urls")),
    path('administration/', include("administration.urls")),
    path('home/clubs', clubs_views.existingClubList, name='exlist'),
    path('home/proposed-clubs', clubs_views.proposedClubList, name='prlist'),
    path('home/joined-clubs', clubs_views.joinedClubList, name='jdlist'),
    path('home/joined-clubs/<int:club_id>/', forum_views.forum_of_club, name='club_forum'),
    path('home/joined-clubs/<int:club_id>/add-event/', forum_views.event_of_club, name='club_event'),
    path('home/joined-clubs/<int:club_id>/list_events/', events_views.list_event_of_club, name='list_club_event'),
    path('home/joined-clubs/<int:event_id>/about', events_views.event_detail1, name='event_detail1'),
    path('home/joined-clubs/<int:club_id>/<int:thread_id>/', forum_views.posts_of_club, name='club_forum_posts'),
    path('home/propose-club', clubs_views.proposeClub, name='prclub'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/',register_views.register, name = 'register'),
    path('home/profile/',profile_views.profile, name = 'profile'),
    path('api/events/',include("events.api.urls")),
    path('api-token-auth/', obtain_jwt_token),
    path("home/profile/change_password",profile_views.change_password, name="change_password"),
    path('emailverify/',register_views.emailverify, name = 'emailverify'),
    path('resetpassword/',register_views.resetpassword,name = 'resetpassword'),
    path('verifyemail/',register_views.verifyemail, name = 'verifyemail'),
    path('reset_password/',register_views.reset_password, name = 'reset_password'),
    path("send",notify_views.send,name='send'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

"""
curl -X POST -d "username=rahul_admin&password=test1234" http://localhost:8000/api-token-auth/
curl -H "Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMiwidXNlcm5hbWUiOiJyYWh1bF9hZG1pbiIsImV4cCI6MTU0NDU2Njc4NywiZW1haWwiOiIifQ.2GoWR9hSMATuh7oVk8f7LzPlxhDn78_mmvr0Tj1A5Hc" http://127.0.0.1:8000/api/events/

"""

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("",views.index)
]

propose_join/urls.py
from django.urls import path
from . import views

app_name= "propose_join"    
urlpatterns=[
   # path('button', views.proposeClub, name='button'),
   # path('list', views.list, name='list'),
    path('home/proposed-clubs/add', views.voting, name='voting'),
    #path('detailview/remove', views.votedown, name='votedown'),
    #path('existing',views.existingclub,name='existing'),
    #path('existing/count', views.passed, name='passed'),
    path('existing/add', views.add_to_join, name='add_to_join'),
    #path('myclub', views.joined, name='myclub'),
    path('detailview/<int:pk>/', views.ProposedClubDetailView.as_view(), name='detailview'),
    path('detailview2/<int:pk>/', views.JoinedClubDetailView.as_view(), name='detailview2'),
    path('detailview2/<int:pk>/rem',views.quitclub,name='quitclub'),
    path('clubmembers/<int:pk>/', views.ListCLubMembers, name="listmem"),



]

home/models.py
from django.db import models

# Create your models here.

propose_join/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from dateutil.relativedelta import relativedelta
from registration.models import Profile
from django.urls import reverse
from datetime import datetime
import datetime
from vote.models import VoteModel


class ProposedClub(VoteModel,models.Model):
    name=models.ForeignKey(User,on_delete=models.PROTECT)
    club_name=models.CharField(max_length=200,unique=True)
    club_info =models.TextField(max_length=20000)
    club_logo=models.ImageField(upload_to='media_/club_logo',)
    date = models.DateTimeField(default=timezone.now, blank=True)
    pollend=models.IntegerField(null=True,blank=True)

    def __str__(self):
        return  str(self.club_name) + " by " + str(self.name)

    def get_url(self):
        return reverse('propose_join:detailview',kwargs={"pk":self.pk})



class ExistingClub(models.Model):
    club_name  = models.CharField(max_length=200,unique=True)
    admin = models.ManyToManyField(User,related_name="club_admins")
    club_info  =models.TextField(max_length=20000)
    club_logo = models.ImageField(upload_to='media_/club_logo', blank=True)
    club_members = models.ManyToManyField(User,related_name="club_members")

    def __str__(self):
        return str(self.club_name) + " admin--> " + str(self.admin)

    def get_url(self):
        return reverse('propose_join:detailview2', kwargs={"pk": self.pk})




# class ClubMember(models.Model):
#     user_name = models.OneToOneField(User,on_delete=models.PROTECT)
#     clubs_joined = models.ManyToManyField(ExistingClub)
#
#     def __str__(self):
#         return str(self.user_name)

propose_join/forms.py
from django import forms
from .models import ProposedClub

class ProposedClubForm(forms.ModelForm):
    class Meta:
        model = ProposedClub
        fields = ('club_name','club_info','club_logo')

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from propose_join.models import ExistingClub
# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return redirect('/home/')
    clubs = ExistingClub.objects.all()
    context = {
        'clubs':clubs,
    }
    return render(request,'home/index.html',context)

propose_join/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import ExistingClub,ProposedClub
from administration.models import Onpollclub
from .forms import ProposedClubForm
from django.contrib.auth import get_user_model
from registration.models import Profile
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.models import UserManager
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.urls import reverse
import datetime, time
from django.utils import timezone
import data as data


def existingClubList(request):
    mem = request.user
    clubs = ExistingClub.objects.exclude(club_name='Global')
   # clubs = clubs1.exclude(club_members=mem)
    paginator = Paginator(clubs,10)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    context = {
        'clubs': clubs,
    }
    return render(request,'propose_join/exlist.html', context)

def proposedClubList(request):
    voter=request.user
    totalstudent=Profile.objects.all().count()
    clubs = Onpollclub.objects.all()
    for i in clubs:
        start=i.date
        milistart=int(time.mktime(start.timetuple())) * 1000
        #print(milistart)
        #print('nf')
        currtime=timezone.now()
        milicurr=(int(time.mktime(currtime.timetuple())) * 1000) + 330*60*1000
        #print(milicurr)
        endtime=int(milistart) + 7*24*60*60*1000
        timeleft=int(endtime - milicurr)
        #print(timeleft)
        i.pollend=timeleft
        i.save()
        for a in clubs:
            if a.pollend<0:
                vote=a.num_vote_up
            #   print(vote)
                threshhold=(vote/totalstudent)*100
                if threshhold >10:
                    instance=ExistingClub.objects.create(club_name=a.club_name, club_info=a.club_info,club_logo=a.club_logo)
                    instance.admin.add(a.name)
                    instance.club_members.add(a.name)
                a.delete()

    clubs = Onpollclub.objects.all()
    paginator = Paginator(clubs,10)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    context = {
        'clubs': clubs,
    }
    return render(request,'propose_join/prlist.html', context)



def joinedClubList(request):
    clubs = ExistingClub.objects.filter(club_members=request.user).exclude(club_name='Global')
    paginator = Paginator(clubs,10)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    context = {
        'clubs': clubs,
    }
    return render(request,'propose_join/jdlist.html', context)


def proposeClub(request):
    form = ProposedClubForm(request.POST, request.FILES)
    if request.method == 'POST':
        form = ProposedClubForm(request.POST, request.FILES)
        #print(request.user)
        #print(request.POST)
        if form.is_valid():
            club1 = form.save(commit=False)
            club1.name = request.user
            #CustomUser.objects.get(Username=request.user)
            club1.save()
            messages.success(request, f'Your Club Has Been Proposed')
            return redirect('user-home')
    else:
        form = ProposedClubForm()
    context = {
            'form' : form,
    }
    return render(request, 'propose_join/home.html', context)


@login_required
def add_to_join(request):
    if request.method == "POST":
        clubname=request.POST.get('club-joined')
     #   print(request.user)
        cuser = request.user
        existingclub = ExistingClub.objects.get(club_name = clubname)
        existingclub.club_members.add(cuser)
        return redirect('exlist')

    else:

        return redirect('user-home')

"""@login_required
def list(request):
    voter=request.user
    totalstudent=Profile.objects.all().count()
    qs = Onpollclub.objects.all()
    for i in qs:
        start=i.date
        milistart=int(time.mktime(start.timetuple())) * 1000
        #print(milistart)
        #print('nf')
        currtime=timezone.now()
        milicurr=(int(time.mktime(currtime.timetuple())) * 1000) + 330*60*1000
        #print(milicurr)
        endtime=int(milistart) + 7*24*60*60*1000
        timeleft=int(endtime - milicurr)
        #print(timeleft)
        i.pollend=timeleft
        i.save()

    for i in qs:

        if i.pollend<0:
            vote=i.num_vote_up
         #   print(vote)

            threshhold=(vote/totalstudent)*100
            if threshhold >10:
                for a in qs:
                    instance=ExistingClub.objects.create(club_name=a.club_name, club_info=a.club_info,club_logo=a.club_logo)
                    instance.admin.add(a.name)


            i.delete()

    qs = Onpollclub.objects.all()





    return render(request, "propose_join/list.html", {"qs": qs})
"""

def voting(request):
    if request.method == "POST":
        club_id =request.POST.get('club-id')
        #print("upvote",club_id)

        cuser=request.user
        user=User.objects.get(username=cuser)
        club1 = Onpollclub.objects.get(pk=club_id)
        action = request.POST.get('vote')
        if action == 'yes':

            club1.votes.up(user.id)
            return redirect(reverse('propose_join:detailview', kwargs={"pk": club_id}))

        elif action == 'no':
            club1.votes.down(user.id)
            return redirect(reverse('propose_join:detailview', kwargs={"pk": club_id}))


        return  redirect (reverse('propose_join:detailview', kwargs={"pk":club_id}))

    else:
        return redirect("user-home")


# def votedown(request):
#     if request.method == "POST":
#         club_id = request.POST.get('club-id')
#         cuser = request.user
#         print("downvote",club_id)
#         user = User.objects.get(username=cuser)
#         club1 = ProposedClub.objects.get(pk=club_id)
#         club1.votes.down(user.id)
#
#         return redirect(reverse('propose_join:detailview', kwargs={"pk": club_id}))
#     else:
#         return redirect("home:index")


class ProposedClubDetailView(DetailView):
    template_name = 'propose_join/proposedclub_detail.html'

    model = Onpollclub
    def get_object(self, queryset=None,*args,**kwargs):
        pk=self.kwargs['pk']
        instance = Onpollclub.objects.get(pk=pk)
        start = instance.date
        milistart = int(time.mktime(start.timetuple())) * 1000
        currtime = timezone.now()
        milicurr = (int(time.mktime(currtime.timetuple())) * 1000) + 330 * 60 * 1000
        endtime = int(milistart) + 7 * 24 * 60 * 60 * 1000
        timeleft = int(endtime - milicurr)
        instance.pollend=timeleft
        end=instance.pollend
        if end < 0:
            vote = instance.num_vote_up
            totalstudent = Profile.objects.all().count()
            threshhold = (vote / totalstudent) * 100
            if threshhold > 10:
                insta = ExistingClub.objects.create(club_name=instance.club_name, club_info=instance.club_info,club_logo=instance.club_logo)
                insta.admin.add(instance.name)
            instance.delete()
            return Onpollclub.DoesNotExist("object doesnt exist")

        else:
            return instance

    def get_context_data(self, **kwargs):
        context = super(ProposedClubDetailView, self).get_context_data(**kwargs)
        pk = self.kwargs['pk']
        instance = Onpollclub.objects.get(pk=pk)
        d = instance.date
        for_js = int(time.mktime(d.timetuple())) * 1000

        #if time.now()
        context['for_js'] = for_js


        return context

    # def update_counter(request):
    #     if request.method == 'POST':
    #         player = Player.objects.get()
    #         player.blur_quantity = request.POST['counter']
    #         player.save()
    #         message = 'update successful'
    #     return HttpResponse(message)

class JoinedClubDetailView(DetailView):
    template_name = 'propose_join/joinedclub_detail.html'

    model = ExistingClub
    def get_object(self, queryset=None,*args,**kwargs):
        pk=self.kwargs['pk']
        try:
            instance = ExistingClub.objects.get(pk=pk)
            return instance

        except:
            return ExistingClub.DoesNotExist("object doesnt exist")

def quitclub(request,pk):

     if request.method == "POST":
            club_id =request.POST.get('club-id')
            cuser=request.user
            user=User.objects.get(username=cuser)
            club1=ExistingClub.objects.get(pk=club_id)
            action = request.POST.get('quit')
            if action == 'quit':

                club1.club_members.remove(user)
                return redirect('jdlist')


def ListCLubMembers(request,pk):
    club = ExistingClub.objects.get(pk=pk)
    if request.method == "POST":
            user_id = request.POST.get('usr')
            print(user_id)
            user = User.objects.get(username = user_id)
            action = request.POST.get('quit')
            if action == 'quit':
                club.club_members.remove(user)
                return redirect('propose_join:listmem', pk = club.id)
    context = {
        'club': club,
    }
    return render(request,'propose_join/club_members.html', context)

propose_join/templates/propose_join/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'forum/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'forum/css/style.css' %}">
    <style>
      a {
        color: #428bca;
      }
      a:hover {
          color: #333;
          text-decoration: none;
      }

      .dropdown {
          position: relative;
          display: inline-block;
      }

      .dropdown-content {
          display: none;
          position: absolute;
          background-color: #f1f1f1;
          min-width: 130px;
          box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
          z-index: 1;
      }

      .dropdown-content a {
          display: block;
      }

      .dropdown-content a:hover {background-color: #ddd;}

      .dropdown:hover .dropdown-content {display: block;}
      </style>
  </head>
  <body>
      <header class="site-header">
          <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top" style="background-color:#001a33;">
            <div class="container">
              <a class="navbar-brand mr-4" href="{% url 'user-home' %}">CLUBSportal</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                  <div class="dropdown">
                    <a class="nav-item nav-link dropbtn" data-toggle="dropdown">Clubs</a>
                    <div class="dropdown-content">
                      <a class="nav-item nav-link" style="color:#001a33" href="{% url 'jdlist' %}">Joined Clubs</a>
                      <a class="nav-item nav-link" style="color:#001a33" href="{% url 'exlist' %}">Existing Clubs</a>
                      <a class="nav-item nav-link" style="color:#001a33" href="{% url 'prlist' %}">Proposed Clubs</a>
                    </div>
                  </div>
                  <a class="nav-item nav-link" href="{% url 'prclub' %}">Propose Club</a>
                  {% if request.user.is_superuser %}
                    <a class="nav-item nav-link" href="{% url 'admin_page' %}">Admin</a>
                  {% endif %}
                  <!--<a class="nav-item nav-link " href="{% url 'post-create' %}">New Post</a>-->
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                  {% if user.is_authenticated %}
                    <a class="nav-item" href="{% url 'profile' %}"> <img class="rounded-circle" style="height: 40px; width: 40px; margin-right: 10px ; margin-top: 1px" src="{{ user.profile.image.url }}"> </a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                  {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </nav>
        </header>
      <main role="main" class="container">
          <div class="row">
            <div class="col-md-8">
                {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{message}}
                    </div>
                {% endfor  %}
            {% endif %}
              {% block body %}{% endblock %}
              {% block comments %}{% endblock %}
            </div>
            <div class="col-md-4">
              <div class="content-section">
                <h3>Our Sidebar</h3>
                {% block link  %}{% endblock %}
              </div>
            </div>
          </div>
        </main>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

  </body>
</html>

propose_join/templates/propose_join/club_members.html
{% extends "propose_join/base.html" %}
{% block body %}
{% for user in club.club_members.all %}
        <article class="media content-section">
            <div class="media">
                <img class="rounded-circle" height="50px" width="50px" src="{{ user.profile.image.url }}">
                <div class="media-body">
                    <h2 class="account-heading" style="margin-left: 50px">{{ user.username }}</h2><br>
                    {% if request.user in club.admin.all %}
                    {% if user not in club.admin.all %}
                    <form class='myclub.url' method="POST" class="form">
                        {% csrf_token %}
                        <input type="hidden" name="club-id" value="{{club.id}}">
                        <input type="hidden" name="usr" value="{{user.username}}">
                        <button type="submit" name="quit" class='btn btn-danger mr-2' style="" value="quit"> Remove </button>
                    </form>
                    {% endif %}
                    {% endif %}
                </div>
        </div>
        </article>
    {% endfor %}
{% endblock %}

propose_join/templates/propose_join/exlist.html
{% extends "propose_join/base.html" %}

{% block body %}

<h2 class="article-title ml-2">EXISTING IIITS CLUBS</h2>
    {% for club in clubs %}
    <div class="content-section">
            <div class="media">
              <img class="rounded-circle account-img" src="{{ club.club_logo.url }}">
              <div class="media-body">
                <h2 class="account-heading"><a href="{{ club.get_url }}">{{ club.club_name }}</a></h2>
                <p class="text-secondary">{{ club.club_info|truncatewords_html:50|urlize }}</p>
                {% if request.user not in club.club_members.all %}
                {% endif %}
            </div>
    </div>
    </div>
    {% endfor %}

{% endblock %}

propose_join/templates/propose_join/home.html
{% extends "propose_join/base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Propose Club
{% endblock %}

{% block body %}
<div class = 'content-section' >
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <fieldset class='form-group' >
            <legend class='border-bottom mb-4'>Propose Your Club</legend>
            {{form|crispy}}
        </fieldset>
        <div class='form-group'>
            <button class= 'btn btn-outline-info' type='submit'>Propose</button>
        </div>
    </form>
</div>
{% endblock %}

propose_join/templates/propose_join/jdlist.html
{% extends "propose_join/base.html" %}

{% block body %}

<h2 class="article-title ml-2">JOINED IIITS CLUBS</h2>
    {% for club in clubs %}
    <div class="content-section">
            <div class="media">
              <img class="rounded-circle account-img" src="{{ club.club_logo.url }}">
              <div class="media-body">
                <h2 class="account-heading"><a href="{{ club.get_url }}">{{ club.club_name }}</a></h2>
                <p class="text-secondary">{{ club.club_info|truncatewords_html:50|urlize }}</p>
            </div>
    </div>
    <center><p class="text-secondary"></p><a class="btn btn-outline-info" style="width: 80%;"href="{% url 'club_forum' club.id %}">Club Forum</a></p></center>
    </div>
    {% endfor %}

{% endblock %}

propose_join/templates/propose_join/joinedclub_detail.html
{% extends "propose_join/base.html" %}

{% block body %}

    <div class="content-section">
            <div class="media">
              <img class="rounded-circle account-img" src="{{ object.club_logo.url }}">
              <div class="media-body">
                <h2 class="account-heading">{{ object.club_name }}</h2>
                <p class="text-secondary">{{ object.club_info|linebreaks|urlize }}</p>
            </div>
            </div>
            {% if request.user in object.club_members.all %}
                <form class='myclub.url' method="POST" action="{% url 'propose_join:quitclub' object.id %}" class="form">
                    {% csrf_token %}
                        <input type="hidden" name="club-id" value="{{object.id}}">
                        <button type="submit" name="quit" class='btn btn-danger' style="width:100%" value="quit">Quit Club </button>
                </form>
                <br>
                     <a href="{% url 'club_forum' object.id %}" class='btn btn-outline-info' style="width:100%" >Visit Club Forum </a>
                </form>
                {% else %}
                <form class="exlist.url" method="POST" action="{% url 'propose_join:add_to_join' %}">
                        {% csrf_token %}
                                <input type="hidden" name="club-joined" value="{{ object.club_name }}">
                                <button type="submit" class="btn btn-success btn-md" style="width:100%">Join Club </button>
                      </form>
                {% endif %}
    </div>

{% endblock %}

{% block link %}
  <p class='text-muted'>
    <ul class="list-group">
      <li class="list-group-item list-group-item-light">Latest Posts</li>
      <li class="list-group-item list-group-item-light">Top Clubs</li>
      <li class="list-group-item list-group-item-light">Top Posts</li>
      {% if request.user in object.admin.all %}
      <li class="list-group-item list-group-item-light"><a class=" btn btn-outline-info" style="width: 100%;"href="{% url 'club_event' object.id %}">Add Event</a></li>
      {% endif %}
    </ul>
  </p>

{% endblock %}

propose_join/templates/propose_join/list.html
{% extends "propose_join/base.html" %}

{% block title %}
    List
{% endblock %}

{% block body %}

{% for q in qs %}
    <div style="min-height: 200px;">
    <h1> Club Name : {{ q.club_name }}</h1>
    <div>
    {% if q.club_logo %}
        <img src="{{ q.club_logo.url }}" alt="" height="100px" width="100px;" style="float: left;">
            {% endif %}
    </div>
    <span style="margin-left: 10px;">

            <ul style="margin-left: 100px;">
      <li> club info :  {{ q.club_info }}</li>
      <h3>Proposed by:      {{ q.name }}</h3>
            </ul>
</div>
{% endfor %}

{% endblock %}

propose_join/templates/propose_join/next.html
{% extends "propose_join/base.html" %}

{% block title %}
    Next
{% endblock %}

{% block body %}
<h1>THANK YOU FOR PROPOSING THE CLUB</h1>
CLICK HERE TO SEE THE PROPOSED CLUB
 <a href="list">click here</a>

{% endblock %}

propose_join/templates/propose_join/prlist.html
{% extends "propose_join/base.html" %}

{% block body %}
<meta http-equiv="refresh" content="20" />
<h2 class="article-title ml-2">PROPOSED IIITS CLUBS</h2>
    {% for club in clubs %}
    <div class="content-section">
            <div class="media">
              <img class="rounded-circle account-img" src="{{ club.club_logo.url }}">
              <div class="media-body">
                <h2 class="account-heading"><a href="{{ club.get_url }}">{{ club.club_name }}</a></h2>
                <p class="text-secondary">{{ club.club_info|truncatewords_html:50|urlize }}</p>
                <form class='list.url' method="POST" action="{% url 'propose_join:voting' %}" data-endpoint="{% url 'propose_join:voting' %}"class="form">
                  {% csrf_token %}
                          <input type="hidden" name="club-id" value="{{club.id}}">
              <button type="submit" name="vote" class='btn btn-success' value="yes">Interested </button>
                               <button type="submit" name="vote" class ='btn btn-danger' value="no"> Not Interested </button>
                </form>
              </div>

    </div>
    </div>
    {% endfor %}

{% endblock %}